/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddListUserDialog.java
 *
 * Created on Jul 26, 2010, 9:59:59 PM
 */

package twitz.ui.dialogs;

import java.awt.Image;
import java.util.Collections;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import org.jdesktop.application.Action;
import twitter4j.User;
import twitter4j.UserList;

/**
 *
 * @author mistik1
 */
public class AddListUserDialog extends javax.swing.JDialog {

	private org.jdesktop.application.ResourceMap resourceMap = twitz.TwitzApp.getContext().getResourceMap(AddListUserDialog.class);
	private javax.swing.ActionMap actionMap = twitz.TwitzApp.getContext().getActionMap(AddListUserDialog.class, this);
	private Map<String, UserList> userListMap = Collections.synchronizedMap(new TreeMap<String, UserList>());
	private User userToBeAdded;
	private UserList selectedList;

    /** Creates new form AddListUserDialog */
    public AddListUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        listPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        userPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        actionToolBar = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(218, 248));
        setName("Form"); // NOI18N

        listPanel.setName("listPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setCellRenderer(new twitz.ui.renderers.UserListRenderer());
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        userPanel.setName("userPanel"); // NOI18N

        
        userLabel.setIcon(resourceMap.getIcon("userLabel.icon")); // NOI18N
        userLabel.setText(resourceMap.getString("userLabel.text")); // NOI18N
        userLabel.setName("userLabel"); // NOI18N

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        actionPanel.setName("actionPanel"); // NOI18N

        actionToolBar.setFloatable(false);
        actionToolBar.setRollover(true);
        actionToolBar.setName("actionToolBar"); // NOI18N

        
        btnAdd.setAction(actionMap.get("addListUser")); // NOI18N
        btnAdd.setIcon(resourceMap.getIcon("btnAdd.icon")); // NOI18N
        btnAdd.setText(resourceMap.getString("btnAdd.text")); // NOI18N
        btnAdd.setFocusable(false);
        btnAdd.setName("btnAdd"); // NOI18N
        actionToolBar.add(btnAdd);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 100));
        actionToolBar.add(jSeparator1);

        btnCancel.setAction(actionMap.get("cancelAddUser")); // NOI18N
        btnCancel.setIcon(resourceMap.getIcon("btnCancel.icon")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setFocusable(false);
        btnCancel.setName("btnCancel"); // NOI18N
        actionToolBar.add(btnCancel);

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents


	@Action
	public void addListUser()
	{
		Object v = jList1.getSelectedValue();
		if(v instanceof UserList)
		{
			this.selectedList = (UserList)v;
		}
		this.dispose();
	}

	@Action
	public void cancelAddUser()
	{
		this.selectedList = null;
		this.dispose();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JToolBar actionToolBar;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables

	public void setUserListMap(Map<String, UserList> map)
	{
		if(map != null)
		{
			this.userListMap = map;
			DefaultListModel model = new DefaultListModel();
			model.clear();
			Set<String> set = map.keySet();
			Iterator<String> iter = set.iterator();
			while (iter.hasNext())
			{
				String string = iter.next();
				model.addElement(map.get(string));
			}
			jList1.setModel(model);
		}
	}

	public void setUser(User user)
	{
		if(user != null)
		{
			this.userToBeAdded = user;
			java.net.URL imgURI = twitz.TwitzApp.verifyImage(user.getProfileImageURL());
			javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURI);
			int status = icon.getImageLoadStatus();

			Image img = icon.getImage().getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
			icon = new ImageIcon(img);
			//ImageIcon icon = new ImageIcon(twitz.TwitzApp.verifyImage(user.getProfileImageURL()));
			userLabel.setIcon(icon);
			userLabel.setText(user.getScreenName());
		}
	}

	public User getUser()
	{
		return this.userToBeAdded;
	}

	public UserList getSelectedUserList()
	{
		return this.selectedList;
	}

	public void setSelectedUserList(UserList userList)
	{
		jList1.setSelectedValue(userList, true);
	}

	public void setButtonText(String string)
	{
		btnAdd.setText(string);
	}

	public void setButtonIcon(ImageIcon imageIcon)
	{
		btnAdd.setIcon(imageIcon);
	}
}
