/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContactsPanel.java
 *
 * Created on Jun 16, 2010, 7:10:25 PM
 */

package twitz.ui;

import java.io.Serializable;
import javax.swing.JDesktopPane;

/**
 *
 * @author mistik1
 */
public class ContactsPanel extends javax.swing.JPanel implements Serializable {

    /** Creates new form ContactsPanel */
    public ContactsPanel() {
        initComponents();
		desktop.add(contacts);
		contacts.setVisible(true);
		contacts.setMaximizable(true);
		desktop.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
		//desktop.getDesktopManager().setBoundsForFrame(contacts, 0, 0, 150, (desktop.getHeight()-50));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();

        setName("Form"); // NOI18N

        desktop.setName("desktop"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
    }// </editor-fold>//GEN-END:initComponents


	public JDesktopPane getDesktop() {
		return desktop;
	}

	public ContactsFrame getContactFrame() {
		return contacts;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    // End of variables declaration//GEN-END:variables

	private ContactsFrame contacts = new ContactsFrame();
}
