/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusPanel.java
 *
 * Created on Jul 1, 2010, 11:54:05 AM
 */

package twitz.ui;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Map;
import java.util.TreeMap;
import twitter4j.PagableResponseList;
import twitter4j.Paging;
import twitter4j.ResponseList;
import twitter4j.Status;
import twitter4j.UserList;
import twitz.events.DefaultTwitzEventModel;
import twitz.events.TwitzEvent;
import twitz.events.TwitzEventModel;
import twitz.events.TwitzEventType;
import twitz.events.TwitzListener;
import twitz.ui.models.StatusListModel;

/**
 *
 * @author mistik1
 */
public class StatusPanel extends javax.swing.JPanel implements TwitzEventModel, java.io.Serializable{

    /** Creates new form StatusPanel */
    public StatusPanel() {
		super();
		resourceMap = twitz.TwitzApp.getContext().getResourceMap(StatusPanel.class);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusScrollPane = new javax.swing.JScrollPane();
        statusList = new twitz.ui.StatusList();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        statusScrollPane.setName("statusScrollPane"); // NOI18N

        statusList.setName("statusList"); // NOI18N
        statusScrollPane.setViewportView(statusList);

        add(statusScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	public void setUserList(UserList list)
	{
		UserList old = this.userlist;
		if(list != null)
		{
			this.userlist = list;
			setInUserList(true);
			this.firePropertyChange("StatusPanelUserListChanged", old, this.userlist);
		}
		else
		{
			this.userlist = null;
			setInUserList(false);
			this.firePropertyChange("StatusPanelUserListChanged", old, this.userlist);
		}
	}

	public UserList getUserList()
	{
		return this.userlist;
	}

	private void setInUserList(boolean val)
	{
		this.isUserList = val;
	}

	public boolean isInUserList()
	{
		return this.isUserList;
	}

	public void setStatusList(StatusList list)
	{
		StatusList old = this.statusList;
		if(list != null)
		{
			this.statusList = list;
			this.firePropertyChange("StatusPanelStatusListChanged", old, this.statusList);
		}
	}

	public StatusList getStatusList()
	{
		return this.statusList;
	}

	public void updateStatus(ResponseList<Status> statuses)
	{
		StatusListModel model = getStatusList().getModel();
		model.clear();
		for(Status s: statuses)
		{
			model.addStatus(s);
		}
	}

	//TwitzEventModel
	public void addTwitzListener(TwitzListener o) {
		dtem.addTwitzListener(o);
	}

	public void removeTwitzListener(TwitzListener o) {
		dtem.removeTwitzListener(o);
	}

	public void fireTwitzEvent(TwitzEvent e) {
		dtem.fireTwitzEvent(e);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private twitz.ui.StatusList statusList;
    private javax.swing.JScrollPane statusScrollPane;
    // End of variables declaration//GEN-END:variables

	private DefaultTwitzEventModel dtem = new DefaultTwitzEventModel();
    private org.jdesktop.application.ResourceMap resourceMap;
	private boolean isUserList = false;
	private UserList userlist = null;

}
