/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TimeLinePanel.java
 *
 * Created on Jul 1, 2010, 2:33:21 PM
 */

package twitz.ui;

import twitter4j.PagableResponseList;
import twitter4j.ResponseList;
import twitter4j.Status;
import twitz.ui.models.StatusListModel;

/**
 *
 * @author mistik1
 */
public class TimeLinePanel extends javax.swing.JPanel {

    /** Creates new form TimeLinePanel */
    public TimeLinePanel() {
		 resourceMap = twitz.TwitzApp.getContext().getResourceMap(TimeLinePanel.class);
		 actionMap = twitz.TwitzApp.getContext().getActionMap(TimeLinePanel.class, this);
        initComponents();
		initDefaults();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagingToolbar = new javax.swing.JToolBar();
        btnTimelinePrev = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnTimelineNext = new javax.swing.JButton();
        timelineToolbar = new javax.swing.JToolBar();
        cmbTimelineType = new javax.swing.JComboBox();
        txtTimelineUser = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        statusScrollPane = new javax.swing.JScrollPane();
        statusList = new twitz.ui.StatusList();

        pagingToolbar.setFloatable(false);
        pagingToolbar.setRollover(true);
        pagingToolbar.setName("pagingToolbar"); // NOI18N
        pagingToolbar.setPreferredSize(new java.awt.Dimension(128, 22));

        btnTimelinePrev.setText(resourceMap.getString("btnTimelinePrev.text")); // NOI18N
        btnTimelinePrev.setToolTipText(resourceMap.getString("btnTimelinePrev.toolTipText")); // NOI18N
        btnTimelinePrev.setFocusable(false);
        btnTimelinePrev.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnTimelinePrev.setName("btnTimelinePrev"); // NOI18N
        btnTimelinePrev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pagingToolbar.add(btnTimelinePrev);

        jSeparator4.setName("jSeparator4"); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(1000, 10));
        pagingToolbar.add(jSeparator4);

        btnTimelineNext.setText(resourceMap.getString("btnTimelineNext.text")); // NOI18N
        btnTimelineNext.setToolTipText(resourceMap.getString("btnTimelineNext.toolTipText")); // NOI18N
        btnTimelineNext.setFocusable(false);
        btnTimelineNext.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnTimelineNext.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnTimelineNext.setName("btnTimelineNext"); // NOI18N
        btnTimelineNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pagingToolbar.add(btnTimelineNext);

        setName("TimeLinePanel"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        timelineToolbar.setFloatable(false);
        timelineToolbar.setRollover(true);
        timelineToolbar.setMinimumSize(new java.awt.Dimension(4, 24));
        timelineToolbar.setName("timelineToolbar"); // NOI18N
        timelineToolbar.setPreferredSize(new java.awt.Dimension(124, 24));

        cmbTimelineType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Home", "User", "Public", "Recent by", "Mentions" }));
        cmbTimelineType.setToolTipText(resourceMap.getString("cmbTimelineType.toolTipText")); // NOI18N
        cmbTimelineType.setMinimumSize(new java.awt.Dimension(100, 24));
        cmbTimelineType.setName("cmbTimelineType"); // NOI18N
        timelineToolbar.add(cmbTimelineType);

        txtTimelineUser.setToolTipText(resourceMap.getString("txtTimelineUser.toolTipText")); // NOI18N
        txtTimelineUser.setEnabled(false);
        txtTimelineUser.setName("txtTimelineUser"); // NOI18N
        timelineToolbar.add(txtTimelineUser);

        btnRefresh.setAction(actionMap.get("doSearch")); // NOI18N
        btnRefresh.setIcon(resourceMap.getIcon("btnRefresh.icon")); // NOI18N
        btnRefresh.setToolTipText(resourceMap.getString("btnRefresh.toolTipText")); // NOI18N
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRefresh.setName("btnRefresh"); // NOI18N
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        timelineToolbar.add(btnRefresh);

        add(timelineToolbar, java.awt.BorderLayout.NORTH);

        statusScrollPane.setName("statusScrollPane"); // NOI18N

        statusList.setModel(new twitz.ui.models.StatusListModel());
        statusList.setName("statusList"); // NOI18N
        statusScrollPane.setViewportView(statusList);

        add(statusScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void initDefaults()
	{
		twitz.TwitzMainView.fixJScrollPaneBarsSize(statusScrollPane);
	}

	public void setStatusList(StatusList list)
	{
		StatusList old = this.statusList;
		if(list != null)
		{
			this.statusList = list;
			this.firePropertyChange("TimeLinePanelStatusListChanged", old, this.statusList);
		}
	}

	public StatusList getStatusList()
	{
		return this.statusList;
	}

	public void setNextCursor(long cursor)
	{
		this.nextCursor = cursor;
	}

	public long getNextCursor()
	{
		return this.nextCursor;
	}

	public void setPrevCursor(long cursor)
	{
		this.prevCursor = cursor;
	}

	public long getPrevCursor()
	{
		return this.prevCursor;
	}

	public void updateStatus(ResponseList<Status> statuses)
	{
		StatusListModel model = getStatusList().getModel();
		model.clear();
		for(Status s: statuses)
		{
			model.addStatus(s);
		}
//		btnTimelinePrev.setEnabled(statuses.hasPrevious());
//		btnTimelineNext.setEnabled(statuses.hasNext());
//		setPrevCursor(statuses.getPreviousCursor());
//		setNextCursor(statuses.getNextCursor());
	}
	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTimelineNext;
    private javax.swing.JButton btnTimelinePrev;
    private javax.swing.JComboBox cmbTimelineType;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar pagingToolbar;
    private twitz.ui.StatusList statusList;
    private javax.swing.JScrollPane statusScrollPane;
    private javax.swing.JToolBar timelineToolbar;
    private javax.swing.JTextField txtTimelineUser;
    // End of variables declaration//GEN-END:variables

    private org.jdesktop.application.ResourceMap resourceMap;
    private javax.swing.ActionMap actionMap;
	private long nextCursor = -1;
	private long prevCursor = -1;
}
