/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TwitzBusyPane.java
 *
 * Created on Jul 25, 2010, 9:49:17 PM
 */

package twitz.ui;

import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import org.jdesktop.application.Action;
import org.jdesktop.swingx.JXPanel;

/**
 *
 * @author Andrew Williams
 */
public class TwitzBusyPane extends JXPanel implements MouseListener{

	org.jdesktop.application.ResourceMap resourceMap = twitz.TwitzApp.getContext().getResourceMap(TwitzBusyPane.class);
	javax.swing.ActionMap actionMap = twitz.TwitzApp.getContext().getActionMap(TwitzBusyPane.class, this);
	javax.swing.JInternalFrame frame;
	java.awt.Component myGlassPane;
	javax.swing.SwingWorker job;
	private boolean blocked = false;

    /** Creates new form TwitzBusyPane */
    public TwitzBusyPane(javax.swing.JInternalFrame blockingFrame, javax.swing.SwingWorker worker)
	{
		this.frame = blockingFrame;
		this.job = worker;
		this.myGlassPane = frame.getGlassPane();
        initComponents();
		busyLabel.setBusy(true);
		this.addMouseListener(this);
		btnCancel.setToolTipText(resourceMap.getString("btnCancel.toolTipText"));
		setAlpha(0.9F);
		jXPanel1.setAlpha(1.0F);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        busyLabel = new org.jdesktop.swingx.JXBusyLabel();
        btnCancel = new javax.swing.JButton();

        
        setToolTipText(resourceMap.getString("TwitzBusyPane.toolTipText")); // NOI18N
        setAlpha(0.5F);
        setFocusable(false);
        setName("TwitzBusyPane"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        jXPanel1.setName("jXPanel1"); // NOI18N
        jXPanel1.setPreferredSize(new java.awt.Dimension(150, 34));

        busyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busyLabel.setText(resourceMap.getString("busyLabel.text")); // NOI18N
        busyLabel.setDirection(org.jdesktop.swingx.JXBusyLabel.Direction.RIGHT);
        busyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        busyLabel.setName("busyLabel"); // NOI18N
        jXPanel1.add(busyLabel);

        
        btnCancel.setAction(actionMap.get("cancel")); // NOI18N
        btnCancel.setIcon(resourceMap.getIcon("btnCancel.icon")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setMaximumSize(new java.awt.Dimension(26, 26));
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.setPreferredSize(new java.awt.Dimension(25, 25));
        jXPanel1.add(btnCancel);

        add(jXPanel1, new java.awt.GridBagConstraints());
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private org.jdesktop.swingx.JXBusyLabel busyLabel;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    // End of variables declaration//GEN-END:variables

	public void setLabelText(String text)
	{
		busyLabel.setText(text);
	}

	public void block()
	{
		if(!(myGlassPane instanceof TwitzBusyPane) && !blocked)
		{
			frame.setGlassPane(this);
			this.setVisible(true);
			blocked = true;
		}
	}

	public void unblock()
	{
		if(!(myGlassPane instanceof TwitzBusyPane) && blocked )
		{
			frame.setGlassPane(myGlassPane);
			this.setVisible(false);
			blocked = false;
		}
	}

	@Action
	public void cancel()
	{
		if(!job.isCancelled() && !job.isDone())
		{
			job.cancel(true);
		}
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
		unblock();
	}

	public void mouseClicked(MouseEvent e)
	{
		Rectangle button = btnCancel.getBounds();
		if(button.contains(e.getPoint()))
		{
			btnCancel.dispatchEvent(e);
		}
		//throw new UnsupportedOperationException("Not supported yet.");
	}

	public void mousePressed(MouseEvent e)
	{
		//throw new UnsupportedOperationException("Not supported yet.");
	}

	public void mouseReleased(MouseEvent e)
	{
		//throw new UnsupportedOperationException("Not supported yet.");
	}

	public void mouseEntered(MouseEvent e)
	{
		Rectangle button = btnCancel.getBounds();
		if(button.contains(e.getPoint()))
		{
			btnCancel.dispatchEvent(e);
		}
		//throw new UnsupportedOperationException("Not supported yet.");
	}

	public void mouseExited(MouseEvent e)
	{
		//throw new UnsupportedOperationException("Not supported yet.");
	}


}
