/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserListPanel.java
 *
 * Created on Jun 17, 2010, 12:08:22 PM
 */

package twitz.ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Vector;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.GroupLayout;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import org.jdesktop.application.Action;
import twitz.TwitzApp;
import twitz.ui.models.ContactsListModel;
import twitz.ui.renderers.ContactsRenderer;
import twitter4j.User;

/**
 *
 * @author mistik1
 */
public class UserListPanel extends javax.swing.JPanel implements MouseListener {

	org.jdesktop.application.ResourceMap resourceMap;
	javax.swing.ActionMap actionMap;

    /** Creates new form UserListPanel */
    public UserListPanel() {
		resourceMap = TwitzApp.getContext().getResourceMap(UserListPanel.class);
		actionMap = TwitzApp.getContext().getActionMap(UserListPanel.class, this);
        initComponents();
		initDefaults();
		setFocusable(true);
		addMouseListener(this);
		
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listPane = new javax.swing.JScrollPane();
        contactsList1 = new twitz.ui.ContactsList();
        toolbar = new javax.swing.JToolBar();
        btnCollapse = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        listName = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setName("UserListPanel"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        listPane.setName("listPane"); // NOI18N

        contactsList1.setCellRenderer(new ContactsRenderer());
        contactsList1.setName("contactsList1"); // NOI18N
        listPane.setViewportView(contactsList1);

        add(listPane, java.awt.BorderLayout.CENTER);

        toolbar.setFloatable(false);
        toolbar.setRollover(true);
        toolbar.setName("toolbar"); // NOI18N
        toolbar.setPreferredSize(new java.awt.Dimension(100, 22));

        btnCollapse.setAction(actionMap.get("toggleCollapsed")); // NOI18N
        btnCollapse.setIcon(resourceMap.getIcon("btnCollapse.icon")); // NOI18N
        btnCollapse.setText(resourceMap.getString("btnCollapse.text")); // NOI18N
        btnCollapse.setToolTipText(resourceMap.getString("btnCollapse.toolTipText")); // NOI18N
        btnCollapse.setFocusable(false);
        btnCollapse.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCollapse.setName("btnCollapse"); // NOI18N
        btnCollapse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnCollapse);

        jSeparator1.setName("jSeparator1"); // NOI18N
        toolbar.add(jSeparator1);

        listName.setText(resourceMap.getString("listName.text")); // NOI18N
        listName.setName("listName"); // NOI18N
        toolbar.add(listName);

        add(toolbar, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

	@Action
	public void toggleCollapsed()
	{
		setCollapsed(!collapsed);
	}

	public void setCollapsed(boolean c) {
		if(collapsed && c) {
			return;
		}
		else if(collapsed && !c) {
			listPane.setVisible(true);
			contactsList1.setVisible(true);
			setPreferredSize(new Dimension(50, boxHeight));
			btnCollapse.setIcon(resourceMap.getIcon("btnCollapse.icon"));
			collapsed = false;
			this.revalidate();
		}
		else if(!collapsed && c) {
			boxHeight = getHeight();
			listPane.setVisible(false);
			contactsList1.setVisible(false);
			setPreferredSize(new Dimension(50, 24));
			btnCollapse.setIcon(resourceMap.getIcon("btnCollapse.down.icon"));
			collapsed = true;
			this.revalidate();
		}
	}

	public boolean isCollapsed() {
		return collapsed;
	}

	private void initDefaults() {
		final ContactsListModel mod = contactsList1.getModel();
		mod.addListDataListener(new ListDataListener() {

			public void intervalAdded(ListDataEvent e)
			{
				setPreferredSize(calcSize(e));
				revalidate();
			}

			public void intervalRemoved(ListDataEvent e)
			{
				setPreferredSize(calcSize(e));
				revalidate();
			}

			public void contentsChanged(ListDataEvent e)
			{
				System.out.println("Inside contentsChanged");
			}

			private Dimension calcSize(ListDataEvent e) {
				int height = 50;
				int count = mod.getSize();
				int newHeight = (count*height);
				Dimension dim = null;
				if(e.getType() == ListDataEvent.INTERVAL_ADDED) {
					dim = new Dimension(50, newHeight < MAX_HEIGHT ? newHeight : MAX_HEIGHT);
				}
				else if(e.getType() == ListDataEvent.INTERVAL_REMOVED) {
					dim = new Dimension(50, newHeight >= MIN_HEIGHT ? newHeight : MIN_HEIGHT);
				}
				logger.log(Level.INFO, "New Dimension for panel: "+dim.toString());
				return dim;
			}
		});
		MouseListener toolbarListener = new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent evt) {
				if(evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
					toggleCollapsed();
				}
			}
		};
		toolbar.addMouseListener(toolbarListener);
		listName.addMouseListener(toolbarListener);
	}

	public ContactsList getContactsList() {
		return contactsList1;
	}

	public void setTitle(String title) {
		listName.setText(title);
	}

	public void addUser(User[] users) {
		contactsList1.addUser(users);
	}
	
	public void addUser(User user) {
		contactsList1.addUser(user);
	}
	
	public void addUser(Vector<User> user) {
		contactsList1.addUser(user);
	}

	public void mouseClicked(MouseEvent e) {
		requestFocusInWindow();
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCollapse;
    private twitz.ui.ContactsList contactsList1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JLabel listName;
    private javax.swing.JScrollPane listPane;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables

	boolean collapsed = false;
	int boxHeight = 350;
	final Logger logger = Logger.getLogger(this.getClass().getName());
	public static final int MAX_HEIGHT = 300;
	public static final int MIN_HEIGHT = 50;

	public void mousePressed(MouseEvent e)
	{
		//throw new UnsupportedOperationException("Not supported yet.");
	}

	public void mouseReleased(MouseEvent e)
	{
		//throw new UnsupportedOperationException("Not supported yet.");
	}

	public void mouseEntered(MouseEvent e)
	{
		//throw new UnsupportedOperationException("Not supported yet.");
	}

	public void mouseExited(MouseEvent e)
	{
		//throw new UnsupportedOperationException("Not supported yet.");
	}

}
